repos:
  - repo: local
    hooks:
      - id: generate-requirements
        name: Generate requirements.txt
        entry: poetry export -f requirements.txt --output requirements.txt --without-hashes
        language: system
        types: [python]
        files: ^pyproject\.toml$
