repos:
  - repo: local
    hooks:
      - id: generate-requirements
        name: Generate requirements.txt
        entry: poetry
        args: [export, --format, requirements.txt, --output, requirements.txt]
        language: system
        pass_filenames: false
