semantic_models:
  # O nome do modelo semântico.
  - name: products
    description: |
      Tabela de dimensão de produtos. O nível de granularidade da tabela é uma linha por produto.
    # O nome do modelo dbt e esquema
    model: ref('products')
    # Entidades. Estas geralmente correspondem às chaves na tabela.
    entities:
      - name: product
        type: primary
        expr: product_id
    # Dimensões. Podem ser categóricas ou de tempo. Elas adicionam contexto adicional às métricas. O padrão típico de consulta é Métrica por Dimensão.
    dimensions:
      - name: product_name
        type: categorical
      - name: product_type
        type: categorical
      - name: product_description
        type: categorical
      - name: is_food_item
        type: categorical
      - name: is_drink_item
        type: categorical
      - name: product_price
        type: categorical
